import type { ExperienciaProfissional } from "@/dominio/experiencia/ExperienciaProfissional";

export const experienciasProfissionais: readonly ExperienciaProfissional[] = [
  {
    id: "grupo-casas-bahia-2026-atual",
    empresa: "Grupo Casas Bahia",
    cargo: "Engenheiro de Software Sênior",
    periodo: "janeiro de 2026 — atual",
    destaque: true,
    logoSrc: "/logos/casas-bahia.jpg",
    logoCorFundo: "#0033CC",
    siteUrl: "https://www.casasbahia.com.br",
    linkedinUrl: "https://www.linkedin.com/company/2977558/",
    resumo:
      "Atuação na manutenção e evolução de microsserviços Java/Spring Boot em ecossistema de e-commerce B2B de alta complexidade, com foco em observabilidade, infraestrutura em nuvem e qualidade das entregas.",
    atividades: [
      "Manutenção e evolução de microsserviços Java/Spring Boot em ecossistema de e-commerce B2B, com stacks de Spring Boot 2.2 a 3.4 (Java 11 a 21).",
      "Migração de 8 sistemas para biblioteca interna de gestão de conexão Redis, padronizando cache e pool entre projetos com stacks distintas, reduzindo código duplicado e aumentando a resiliência de conexão.",
      "Diagnóstico e correção de bugs de produção identificados via observabilidade com Dynatrace, resultando em mensagens de erro mais específicas e redução de chamados de suporte.",
      "Ajustes de infraestrutura em Kubernetes (AKS/Azure), incluindo HPA, probes e tuning de JVM, além de correção de restarts por falta de memória, aumentando a estabilidade e disponibilidade das aplicações em produção.",
      "Correção de vulnerabilidades (CVEs) em imagens Docker e troubleshooting de pipelines de CI/CD (GitHub Actions, XL-Release), desbloqueando esteiras de deploy travadas e reduzindo a exposição a vulnerabilidades.",
      "Condução de demandas via Jira, abertura de Pull Requests e colaboração entre squads.",
    ],
    tecnologias: [
      "Java",
      "Spring Boot",
      "Kubernetes",
      "Azure (AKS)",
      "Redis",
      "Docker",
      "Dynatrace",
      "GitHub Actions",
    ],
    competencias: [
      "Microsserviços Java/Spring Boot",
      "Observabilidade e diagnóstico",
      "Infraestrutura Kubernetes e Cloud",
      "Segurança e CI/CD",
      "Colaboração entre squads",
    ],
  },
  {
    id: "matera-2025-2026",
    empresa: "Matera",
    cargo: "Desenvolvedor Full Stack",
    periodo: "fevereiro de 2025 — janeiro de 2026",
    logoSrc: "/logos/matera.png",
    logoCorFundo: "#461CDC",
    siteUrl: "https://www.matera.com",
    linkedinUrl: "https://www.linkedin.com/company/12614/",
    resumo:
      "Atuação na modernização, segurança e operação de aplicações Java e microsserviços em ambiente corporativo, com deploys e observabilidade em infraestrutura AWS.",
    atividades: [
      "Atualização e migração de versões do Spring Framework/Spring Boot e do Java (11 a 21) em aplicações críticas, corrigindo breaking changes e mantendo compatibilidade com integrações internas.",
      "Identificação e correção de vulnerabilidades relacionadas a OWASP, CVEs e dependências, acompanhando cobertura e qualidade do código com SonarQube e JaCoCo.",
      "Migração de pipelines de deploy do Jenkins para rodar sobre infraestrutura AWS (EKS), com publicação de imagens Docker via ECR e versionamento de charts com Helm, reduzindo o tempo entre merge e produção.",
      "Configuração de observabilidade das aplicações com AWS CloudWatch (logs e métricas), agilizando a identificação de falhas em produção após os deploys.",
      "Implementação de autenticação e autorização centralizada com Keycloak, integrando segredos de configuração ao AWS Secrets Manager para evitar credenciais expostas em código.",
      "Refatoração de código legado com SOLID e Clean Code, otimização de queries e procedures PL/SQL, e ampliação da cobertura de testes com JUnit e Testcontainers.",
    ],
    tecnologias: [
      "Java",
      "Spring Boot",
      "AWS (EKS)",
      "Docker",
      "Kubernetes",
      "Keycloak",
      "PL/SQL",
      "JUnit",
    ],
    competencias: [
      "Modernização de aplicações",
      "Segurança de software",
      "Cloud AWS",
      "Testes automatizados",
      "Autenticação e autorização",
      "Qualidade de código",
    ],
  },
  {
    id: "200dev-2024-2025",
    empresa: "200DEV",
    clientes: [
      { nome: "Banco BV", logoSrc: "/logos/bv.png", url: "https://www.bv.com.br", bordaClara: true },
      { nome: "Ipiranga", logoSrc: "/logos/ipiranga.png", url: "https://www.ipiranga.com.br" },
    ],
    cargo: "Desenvolvedor Web/Java",
    periodo: "abril de 2024 — janeiro de 2025",
    logoSrc: "/logos/200dev.jpg",
    logoCorFundo: "#070930",
    siteUrl: "https://200dev.com.br",
    linkedinUrl: "https://www.linkedin.com/company/72466372/",
    resumo:
      "Desenvolvimento, sustentação e evolução de aplicações Java para clientes do setor financeiro (Banco BV e Ipiranga), com foco em segurança, integrações assíncronas e processamento automatizado de arquivos.",
    atividades: [
      "Correção de vulnerabilidades críticas identificadas em aplicações Java do setor financeiro, atendendo a prazos de criticidade definidos por auditorias de segurança e reduzindo o risco de exposição em produção.",
      "Evolução de APIs REST para o Banco BV e Ipiranga, documentando contratos com Swagger/OpenAPI e padronizando respostas de erro para facilitar a integração com sistemas parceiros.",
      "Desenvolvimento de processos batch para leitura, validação e processamento de arquivos financeiros, com tratamento de falhas e reprocessamento automático em caso de inconsistência nos dados.",
      "Integração assíncrona entre sistemas via RabbitMQ, desacoplando serviços de processamento e reduzindo o impacto de picos de carga sobre as APIs síncronas.",
      "Diagnóstico e correção de instabilidades em produção, ampliando a cobertura de testes unitários com JUnit para prevenir regressões em fluxos críticos.",
      "Aplicação de práticas de segurança específicas do setor financeiro, como validação de dados sensíveis e controle de acesso, em conjunto com as squads de compliance.",
    ],
    tecnologias: [
      "Java",
      "APIs REST",
      "RabbitMQ",
      "Swagger/OpenAPI",
      "JUnit",
      "Processos batch",
    ],
    competencias: [
      "Segurança de aplicações",
      "Integração entre sistemas",
      "Processamento batch",
      "Mensageria",
      "Testes automatizados",
      "Compliance financeiro",
    ],
  },
  {
    id: "cbyk-consultoria-2024",
    empresa: "CBYK Consultoria",
    logoSrc: "/logos/cbyk.jpg",
    clientes: [
      {
        nome: "Ministério da Cidadania",
        logoSrc: "/logos/ministerio-cidadania.png",
        url: "https://www.gov.br/cidadania",
      },
      { nome: "Vibra", logoSrc: "/logos/vibra.png", url: "https://www.vibraenergia.com.br" },
      { nome: "TJ-BA", logoSrc: "/logos/tjba.png", url: "https://www.tjba.jus.br" },
    ],
    siteUrl: "https://cbyk.com/",
    linkedinUrl: "https://www.linkedin.com/company/cbyk-consultoria/",
    cargo: "Desenvolvedor Web/Java",
    periodo: "janeiro de 2024 — abril de 2024",
    resumo:
      "Desenvolvimento de microsserviços cloud-native e arquiteturas orientadas a eventos para clientes como Ministério da Cidadania, Vibra e TJ-BA, com foco em performance, desacoplamento, testabilidade e observabilidade.",
    atividades: [
      "Desenvolvimento e evolução de microsserviços com Quarkus e Spring Boot, aplicando Arquitetura Hexagonal para isolar regras de negócio das integrações externas de cada cliente.",
      "Implementação de arquitetura orientada a eventos com Apache Kafka, desacoplando serviços e absorvendo picos de processamento sem impactar as APIs síncronas.",
      "Construção de APIs REST reativas documentadas com Swagger/OpenAPI, integradas a PostgreSQL e MySQL, com uso de Redis para cache de consultas frequentes e redução do tempo de resposta em endpoints críticos.",
      "Implementação de logs, métricas e rastreamento distribuído entre microsserviços, facilitando o diagnóstico de falhas em ambientes com múltiplos serviços containerizados (Docker/Kubernetes).",
      "Ampliação da cobertura de testes com JUnit e Mockito, e participação ativa em code reviews para manter a aderência a SOLID e Clean Code entre as squads.",
      "Otimização de containers Docker e ajustes de configuração em Kubernetes, reduzindo o tempo de subida dos serviços em ambiente de homologação.",
    ],
    tecnologias: [
      "Java",
      "Quarkus",
      "Spring Boot",
      "Apache Kafka",
      "Arquitetura Hexagonal",
      "APIs REST",
      "Swagger/OpenAPI",
      "Docker",
      "Kubernetes",
      "PostgreSQL",
      "MySQL",
      "Redis",
      "JUnit",
      "Mockito",
    ],
    competencias: [
      "Arquitetura orientada a eventos",
      "Cloud-native",
      "Arquitetura hexagonal",
      "Observabilidade",
      "Performance",
      "Testes automatizados",
    ],
  },
  {
    id: "atos-2022-2024",
    empresa: "Atos",
    logoSrc: "/logos/atos.png",
    logoBordaClara: true,
    clientes: [
      {
        nome: "Banco Bradesco",
        logoSrc: "/logos/bradesco.png",
        url: "https://www.bradesco.com.br",
        bordaClara: true,
        corFundo: "#E5173F",
      },
      { nome: "Elo Cartões", logoSrc: "/logos/elo.png", url: "https://www.cartaoelo.com.br" },
      { nome: "B3 - Bolsa de Valores", logoSrc: "/logos/b3.png", url: "https://www.b3.com.br" },
    ],
    siteUrl: "https://atos.net/pt-pt/portugal",
    linkedinUrl: "https://www.linkedin.com/company/atos/",
    cargo: "Desenvolvedor Web/Java",
    periodo: "julho de 2022 — janeiro de 2024",
    resumo:
      "Atuação em sistemas corporativos e financeiros para clientes como Banco Bradesco, Elo Cartões e B3, desenvolvendo microsserviços, integrações seguras e comunicação entre plataformas modernas e sistemas legados.",
    atividades: [
      "Desenvolvimento e sustentação de microsserviços para clientes como Banco Bradesco, Elo Cartões e B3, integrando sistemas distribuídos modernos a mainframes legados via RMI.",
      "Integração assíncrona entre sistemas com Kafka e RabbitMQ, permitindo o processamento de eventos financeiros sem acoplar diretamente os serviços consumidores.",
      "Uso de Redis para cache e controle de idempotência em operações financeiras críticas, evitando o processamento duplicado de transações em cenários de reenvio.",
      "Uso de MongoDB para armazenar eventos e dados semiestruturados, apoiando fluxos de auditoria e rastreabilidade das integrações entre plataformas.",
      "Implementação de comunicação segura entre microsserviços e padronização de logs, facilitando a rastreabilidade de falhas em produção em clusters executados na Azure.",
      "Containerização e orquestração dos microsserviços, com testes unitários e de integração para garantir a estabilidade das entregas em ambiente de alta criticidade.",
    ],
    tecnologias: [
      "Java",
      "APIs REST",
      "Kafka",
      "RabbitMQ",
      "RMI",
      "Redis",
      "MongoDB",
      "Azure",
      "Docker",
      "Kubernetes",
      "Testes automatizados",
    ],
    competencias: [
      "Sistemas distribuídos",
      "Integrações corporativas",
      "Mensageria",
      "Idempotência",
      "Segurança",
      "Observabilidade",
      "Cloud",
    ],
  },
  {
    id: "blendit-2022",
    empresa: "BlendIt",
    logoSrc: "/logos/blendit.png",
    clientes: [
      {
        nome: "Santander",
        logoSrc: "/logos/santander.png",
        url: "https://www.santander.com.br",
        bordaClara: true,
      },
    ],
    siteUrl: "https://blendit.com/",
    linkedinUrl: "https://www.linkedin.com/company/blend-it-srl/",
    cargo: "Desenvolvedor Full Stack",
    periodo: "fevereiro de 2022 — julho de 2022",
    resumo:
      "Atuação em aplicação do setor bancário do Santander, evoluindo APIs REST com Java e Spring Boot, ampliando testes automatizados e desenvolvendo funcionalidades backend e frontend com Angular.",
    atividades: [
      "Desenvolvimento e evolução de APIs REST com Java e Spring Boot para aplicação do setor bancário do Santander, implementando novas funcionalidades e mantendo compatibilidade com integrações existentes.",
      "Ampliação da cobertura de testes com JUnit e Mockito, reduzindo regressões em fluxos críticos de transações antes de cada release.",
      "Integração com MongoDB para persistência de dados semiestruturados, com modelagem voltada às consultas mais frequentes da aplicação.",
      "Implementação de comunicação assíncrona por mensageria entre serviços backend, desacoplando processos de maior latência do fluxo principal de requisições.",
      "Desenvolvimento de interfaces com Angular, integrando o frontend às APIs backend e ajustando componentes conforme feedback de UX das squads de produto.",
      "Participação em revisões de código e aplicação de boas práticas de desenvolvimento, contribuindo para a padronização do time full stack.",
    ],
    tecnologias: [
      "Java",
      "Spring Boot",
      "APIs REST",
      "JUnit",
      "Mockito",
      "MongoDB",
      "Mensageria",
      "Angular",
    ],
    competencias: [
      "Desenvolvimento full stack",
      "Qualidade de software",
      "Integração frontend/backend",
      "Testes automatizados",
      "APIs",
      "Mensageria",
    ],
  },
  {
    id: "plennus-ti-2019-2022",
    empresa: "Plennus TI",
    logoSrc: "/logos/plennus.jpg",
    clientes: [
      { nome: "Centro de Computação da Aeronáutica (RJ)", logoSrc: "/logos/cca-rj.jpg" },
    ],
    siteUrl: "https://plennusti.com/",
    linkedinUrl: "https://www.linkedin.com/company/plennusti/",
    cargo: "Desenvolvedor Full Stack",
    periodo: "janeiro de 2019 — fevereiro de 2022",
    resumo:
      "Atuação na sustentação e evolução de sistemas corporativos críticos para o Centro de Computação da Aeronáutica (RJ), combinando tecnologias Java legadas e modernas.",
    atividades: [
      "Desenvolvimento e manutenção de sistemas críticos em Java EE para o Centro de Computação da Aeronáutica (RJ), atuando com Spring MVC, JSF, JSP, PrimeFaces e RichFaces em aplicações com grande volume de usuários.",
      "Migração gradual do acesso a dados baseado em JDBC para Hibernate/JPA, reduzindo código boilerplate e padronizando o acesso ao banco entre os módulos do sistema.",
      "Persistência com Hibernate, Criteria API e queries nativas, otimizando consultas nas telas com maior volume de acesso simultâneo.",
      "Desenvolvimento de novas APIs REST com Spring Boot para expor funcionalidades legadas a novas interfaces, viabilizando a modernização gradual do sistema sem interromper a operação.",
      "Desenvolvimento de interfaces com AngularJS e participação em projetos com React e Angular, apoiando a transição de telas legadas para uma stack de frontend mais moderna.",
      "Correção de bugs e melhoria de performance em fluxos críticos, colaborando com equipes técnicas e áreas de negócio para priorizar as evoluções do sistema.",
    ],
    tecnologias: [
      "Java EE",
      "Spring MVC",
      "Spring Boot",
      "JSF",
      "JSP",
      "PrimeFaces",
      "RichFaces",
      "Hibernate",
      "JPA",
      "JDBC",
      "AngularJS",
      "Angular",
      "React",
      "APIs REST",
    ],
    competencias: [
      "Modernização de legados",
      "Sustentação de sistemas críticos",
      "Persistência de dados",
      "Desenvolvimento full stack",
      "Performance",
      "Evolução de aplicações corporativas",
    ],
  },
];
