import type { ExperienciaProfissional } from "@/dominio/experiencia/ExperienciaProfissional";

export const experienciasProfissionais: readonly ExperienciaProfissional[] = [
  {
    id: "grupo-casas-bahia-2026-atual",
    empresa: "Grupo Casas Bahia",
    cargo: "Engenheiro de Software Sênior",
    periodo: "janeiro de 2026 — atual",
    destaque: true,
    resumo:
      "Atuação na construção e evolução de uma plataforma corporativa de pedidos, desenvolvendo serviços backend, integrações e componentes distribuídos em ambiente de alta complexidade.",
    atividades: [
      "Desenvolvimento e evolução de aplicações backend com Java 17 e Spring.",
      "Construção e manutenção de APIs e serviços distribuídos.",
      "Integração assíncrona utilizando Apache Kafka.",
      "Implementação de testes unitários.",
      "Documentação de APIs com Swagger/OpenAPI.",
      "Integração com SQL Server e MongoDB.",
      "Containerização com Docker.",
      "Execução e sustentação em OpenShift e Kubernetes.",
      "Participação em fluxo de trabalho baseado em Kanban.",
      "Apoio à qualidade e à integração contínua das entregas.",
    ],
    tecnologias: [
      "Java 17",
      "Spring",
      "Apache Kafka",
      "SQL Server",
      "MongoDB",
      "OpenShift",
      "Kubernetes",
      "Docker",
      "Swagger/OpenAPI",
      "Testes unitários",
    ],
    competencias: [
      "Backend enterprise",
      "Sistemas distribuídos",
      "Integração assíncrona",
      "Qualidade de software",
      "Entrega contínua",
    ],
  },
  {
    id: "matera-2025-2026",
    empresa: "Matera",
    cargo: "Desenvolvedor Full Stack",
    periodo: "fevereiro de 2025 — janeiro de 2026",
    resumo:
      "Atuação na modernização, evolução, segurança e operação de aplicações Java e microsserviços em ambiente corporativo e cloud.",
    atividades: [
      "Atualização e migração de versões do Spring Framework e Spring Boot.",
      "Identificação e correção de vulnerabilidades relacionadas a OWASP, CVEs e dependências.",
      "Refatoração de código legado com SOLID e Clean Code.",
      "Desenvolvimento e otimização de procedures e queries PL/SQL.",
      "Implementação de testes unitários e de integração com JUnit.",
      "Uso de Testcontainers para simulação de dependências reais.",
      "Análise de qualidade e cobertura com SonarQube e JaCoCo.",
      "Migração e evolução de pipelines Jenkins integrados à AWS.",
      "Realização de deploys utilizando AWS e Helm.",
      "Implementação de autenticação e autorização com Keycloak.",
      "Containerização com Docker.",
      "Gerenciamento de aplicações em Kubernetes.",
    ],
    tecnologias: [
      "Java",
      "Spring Framework",
      "Spring Boot",
      "PL/SQL",
      "JUnit",
      "Testcontainers",
      "SonarQube",
      "JaCoCo",
      "Jenkins",
      "AWS",
      "Helm",
      "Keycloak",
      "Docker",
      "Kubernetes",
    ],
    competencias: [
      "Modernização de aplicações",
      "Segurança de software",
      "Testes automatizados",
      "Cloud e DevOps",
      "Qualidade de código",
      "Autenticação e autorização",
    ],
  },
  {
    id: "200dev-2024-2025",
    empresa: "200DEV",
    cargo: "Desenvolvedor Web/Java",
    periodo: "abril de 2024 — janeiro de 2025",
    resumo:
      "Desenvolvimento, sustentação e evolução de aplicações Java do setor financeiro, com foco em segurança, microsserviços, integrações e processamento automatizado.",
    atividades: [
      "Correção de vulnerabilidades críticas em aplicações Java.",
      "Evolução e desenvolvimento de APIs REST.",
      "Documentação de APIs com Swagger/OpenAPI.",
      "Implementação e manutenção de microsserviços.",
      "Desenvolvimento de processos batch para leitura, validação e processamento de arquivos.",
      "Integração assíncrona entre sistemas utilizando RabbitMQ.",
      "Implementação de testes unitários com JUnit.",
      "Melhoria contínua de performance, confiabilidade e estabilidade.",
      "Aplicação de práticas de segurança voltadas ao setor financeiro.",
    ],
    tecnologias: [
      "Java",
      "APIs REST",
      "Swagger/OpenAPI",
      "Microsserviços",
      "RabbitMQ",
      "Processos batch",
      "JUnit",
    ],
    competencias: [
      "Segurança de aplicações",
      "Integração entre sistemas",
      "Processamento batch",
      "Mensageria",
      "Testes automatizados",
      "Sustentação técnica",
    ],
  },
  {
    id: "cbyk-consultoria-2024",
    empresa: "CBYK Consultoria",
    cargo: "Desenvolvedor Web/Java",
    periodo: "janeiro de 2024 — abril de 2024",
    resumo:
      "Desenvolvimento de microsserviços cloud-native e arquiteturas orientadas a eventos, com foco em performance, desacoplamento, testabilidade e observabilidade.",
    atividades: [
      "Desenvolvimento e evolução de microsserviços com Quarkus e Spring Boot.",
      "Implementação de arquitetura orientada a eventos.",
      "Utilização de Apache Kafka para comunicação assíncrona.",
      "Aplicação de Arquitetura Hexagonal.",
      "Construção de APIs REST reativas.",
      "Documentação com Swagger/OpenAPI.",
      "Otimização de containers Docker.",
      "Execução de aplicações em Kubernetes.",
      "Integração com PostgreSQL e MySQL.",
      "Uso de Redis para cache.",
      "Implementação de testes com JUnit e Mockito.",
      "Participação em code reviews.",
      "Aplicação de SOLID e Clean Code.",
      "Apoio à implementação de logs, métricas e rastreamento distribuído.",
    ],
    tecnologias: [
      "Java",
      "Quarkus",
      "Spring Boot",
      "Apache Kafka",
      "Arquitetura Hexagonal",
      "APIs REST",
      "Swagger/OpenAPI",
      "Docker",
      "Kubernetes",
      "PostgreSQL",
      "MySQL",
      "Redis",
      "JUnit",
      "Mockito",
    ],
    competencias: [
      "Arquitetura orientada a eventos",
      "Cloud-native",
      "Arquitetura hexagonal",
      "Observabilidade",
      "Performance",
      "Testes automatizados",
    ],
  },
  {
    id: "atos-2022-2024",
    empresa: "Atos",
    cargo: "Desenvolvedor Web/Java",
    periodo: "julho de 2022 — janeiro de 2024",
    resumo:
      "Atuação em sistemas corporativos e financeiros, desenvolvendo microsserviços, integrações seguras e comunicação entre plataformas modernas e sistemas legados.",
    atividades: [
      "Desenvolvimento de funcionalidades e sustentação de microsserviços.",
      "Integração assíncrona utilizando Kafka e RabbitMQ.",
      "Construção e manutenção de APIs REST.",
      "Integração entre sistemas distribuídos e mainframe.",
      "Comunicação com sistemas legados utilizando RMI.",
      "Uso de Redis para cache e controle de idempotência.",
      "Uso de MongoDB para eventos e dados semiestruturados.",
      "Implementação de comunicação segura entre microsserviços.",
      "Padronização de logs e rastreabilidade.",
      "Atuação com aplicações executadas em clusters Azure.",
      "Implementação de testes unitários e de integração.",
      "Atuação com microsserviços containerizados e orquestrados.",
    ],
    tecnologias: [
      "Java",
      "APIs REST",
      "Kafka",
      "RabbitMQ",
      "RMI",
      "Redis",
      "MongoDB",
      "Azure",
      "Docker",
      "Kubernetes",
      "Testes automatizados",
    ],
    competencias: [
      "Sistemas distribuídos",
      "Integrações corporativas",
      "Mensageria",
      "Idempotência",
      "Segurança",
      "Observabilidade",
      "Cloud",
    ],
  },
  {
    id: "blendit-2022",
    empresa: "BlendIt",
    cargo: "Desenvolvedor Full Stack",
    periodo: "fevereiro de 2022 — julho de 2022",
    resumo:
      "Atuação em aplicação do setor bancário, evoluindo APIs, ampliando testes automatizados e desenvolvendo funcionalidades backend e frontend.",
    atividades: [
      "Desenvolvimento e evolução de APIs REST com Java e Spring Boot.",
      "Implementação de novas funcionalidades.",
      "Manutenção e evolução de serviços existentes.",
      "Ampliação da cobertura de testes com JUnit e Mockito.",
      "Integração com MongoDB.",
      "Implementação de comunicação assíncrona por mensageria.",
      "Desenvolvimento de interfaces com Angular.",
      "Integração entre frontend e APIs backend.",
      "Participação em revisões de código.",
      "Aplicação de boas práticas de desenvolvimento.",
    ],
    tecnologias: [
      "Java",
      "Spring Boot",
      "APIs REST",
      "JUnit",
      "Mockito",
      "MongoDB",
      "Mensageria",
      "Angular",
    ],
    competencias: [
      "Desenvolvimento full stack",
      "Qualidade de software",
      "Integração frontend/backend",
      "Testes automatizados",
      "APIs",
      "Mensageria",
    ],
  },
  {
    id: "plennus-ti-2019-2022",
    empresa: "Plennus TI",
    cargo: "Desenvolvedor Full Stack",
    periodo: "janeiro de 2019 — fevereiro de 2022",
    resumo:
      "Atuação na sustentação e evolução de sistemas corporativos críticos, combinando tecnologias Java legadas e modernas.",
    atividades: [
      "Desenvolvimento e manutenção de sistemas com Java EE.",
      "Atuação com Spring MVC, JSF, JSP, PrimeFaces e RichFaces.",
      "Implementação de novas funcionalidades em aplicações web corporativas.",
      "Persistência com Hibernate, Criteria API e queries nativas.",
      "Migração de acesso a dados baseado em JDBC para Hibernate/JPA.",
      "Desenvolvimento de APIs REST com Spring Boot.",
      "Desenvolvimento de interfaces em AngularJS.",
      "Participação em projetos com React e Angular.",
      "Correção de bugs.",
      "Melhoria de performance.",
      "Evolução de sistemas com grande volume de usuários.",
      "Colaboração com equipes técnicas e áreas de negócio.",
    ],
    tecnologias: [
      "Java EE",
      "Spring MVC",
      "Spring Boot",
      "JSF",
      "JSP",
      "PrimeFaces",
      "RichFaces",
      "Hibernate",
      "JPA",
      "JDBC",
      "AngularJS",
      "Angular",
      "React",
      "APIs REST",
    ],
    competencias: [
      "Modernização de legados",
      "Sustentação de sistemas críticos",
      "Persistência de dados",
      "Desenvolvimento full stack",
      "Performance",
      "Evolução de aplicações corporativas",
    ],
  },
];
