import type { Projeto } from "@/dominio/projeto/Projeto";

export const projetosEmDestaque: readonly Projeto[] = [
  {
    id: "wepdev-portfolio",
    slug: "wepdev-portfolio",
    nome: "WEPDEV Portfolio",
    categoria: "Produto e Engenharia de Software",
    descricao:
      "Plataforma pública para apresentar trajetória profissional, competências técnicas, projetos, decisões arquiteturais e práticas de Engenharia de Software.",
    problema:
      "Um currículo tradicional apresenta experiências e tecnologias, mas não demonstra com profundidade como um profissional organiza, documenta, implementa e evolui um produto de software.",
    solucao:
      "O produto está sendo desenvolvido de forma incremental, com documentação versionada, especificações por épicos, desenvolvimento assistido por IA, validação técnica e histórico de commits semânticos.",
    tecnologias: [
      "Next.js 16",
      "React 19",
      "TypeScript",
      "Tailwind CSS 4",
      "App Router",
      "Server Components",
      "Git",
      "GitHub",
    ],
    conceitos: [
      "Componentização",
      "Design System",
      "Acessibilidade",
      "Responsividade",
      "Documentação orientada por especificações",
      "Desenvolvimento incremental",
      "Commits semânticos",
      "Separação de responsabilidades",
      "Desenvolvimento assistido por IA",
      "Segurança de conteúdo público",
    ],
    estado: "em-evolucao",
    tipo: "produto",
    repositorioUrl: "https://github.com/wep1980/wepdev-portfolio",
    destaque: true,
    chamadaPrincipal: "Ver repositório",
    chamadaSecundaria: "Estudo de caso em construção",
  },
  {
    id: "laboratorio-java-ia",
    slug: "laboratorio-java-ia",
    nome: "Laboratório Java com IA",
    categoria: "Java e Inteligência Artificial",
    descricao:
      "Projeto planejado para experimentar e comparar modelos de Inteligência Artificial em aplicações Java.",
    problema:
      "Desenvolvedores Java precisam integrar modelos de linguagem a aplicações empresariais, mas muitas demonstrações dependem exclusivamente de APIs pagas, não comparam modelos e não apresentam métricas úteis para tomada de decisão.",
    solucao:
      "A proposta prioriza Ollama como opção local, OpenAI como integração opcional, comparação de respostas, medição de tempo, estimativa de tokens e custo quando aplicável, registro de avaliações, experimentos com prompts e evolução futura para RAG.",
    tecnologias: [
      "Java 21",
      "Spring Boot",
      "Spring AI",
      "Ollama",
      "OpenAI opcional",
      "Maven",
      "PostgreSQL",
      "Docker",
      "OpenAPI",
      "Testes automatizados",
    ],
    conceitos: [
      "Integração com modelos generativos",
      "Abstração entre provedores",
      "Execução local de modelos",
      "Comparação de respostas",
      "Métricas de latência",
      "Controle de custo",
      "Avaliação de resultados",
      "Arquitetura modular",
      "RAG em etapa futura",
    ],
    estado: "planejado",
    tipo: "laboratorio",
    destaque: true,
    chamadaPrincipal: "Projeto planejado",
    chamadaSecundaria: "Acompanhar evolução futura",
    tecnologiasPlanejadas: true,
    conceitosPlanejados: true,
  },
  {
    id: "plataforma-java-microsservicos",
    slug: "plataforma-java-microsservicos",
    nome: "Plataforma Java de Microsserviços",
    categoria: "Backend Enterprise",
    descricao:
      "Estudo de caso planejado para demonstrar uma arquitetura backend corporativa moderna com serviços Java independentes.",
    problema:
      "Projetos backend frequentemente demonstram apenas uma API isolada, sem representar desafios reais de integração, mensageria, segurança, observabilidade, persistência e entrega contínua.",
    solucao:
      "A proposta é criar uma plataforma autoral com APIs REST, comunicação assíncrona, persistência, segurança, testes automatizados, containers, observabilidade, documentação e automação de entrega. A lista técnica será refinada antes da implementação para evitar complexidade desnecessária.",
    tecnologias: [
      "Java 21",
      "Spring Boot",
      "Quarkus",
      "Apache Kafka",
      "RabbitMQ",
      "PostgreSQL",
      "MongoDB",
      "Redis",
      "Docker",
      "Kubernetes",
      "OpenAPI",
      "Keycloak",
      "OpenTelemetry",
      "Maven",
      "GitHub Actions",
    ],
    conceitos: [
      "Microsserviços",
      "Arquitetura orientada a eventos",
      "Integração assíncrona",
      "Idempotência",
      "Resiliência",
      "Segurança",
      "Autenticação e autorização",
      "Observabilidade",
      "Persistência poliglota",
      "Testes unitários e de integração",
      "CI/CD",
      "Documentação de APIs",
    ],
    estado: "planejado",
    tipo: "estudo-de-caso",
    destaque: true,
    chamadaPrincipal: "Estudo de caso planejado",
    chamadaSecundaria: "Arquitetura em definição",
    tecnologiasPlanejadas: true,
    conceitosPlanejados: true,
  },
];
